from __future__ import annotations

import os

from agents.github_client import GitHubClient

LABELS = {
    "market-signal": ("1d76db", "Public market evidence"),
    "idea": ("5319e7", "Venture idea"),
    "tool-request": ("fbca04", "Dependency or tool approval"),
    "feature-request": ("84b6eb", "Product feature request"),
    "bug": ("d73a4a", "Confirmed or reported bug"),
    "feedback": ("0e8a16", "User feedback"),
    "agent-request": ("0052cc", "Request an agent run"),
    "founder-approval": ("b60205", "Founder decision required"),
    "requires-approval": ("b60205", "Human approval required"),
    "agent-generated": ("bfdadc", "Generated by ZeroFounder"),
    "experiment": ("c5def5", "Growth or validation experiment"),
    "pivot-review": ("d4c5f9", "Pivot prerequisites and review"),
    "high-risk": ("8b0000", "High-risk action; never autonomous"),
}


def main() -> int:
    GitHubClient(os.environ["GITHUB_TOKEN"], os.environ["GITHUB_REPOSITORY"]).ensure_labels(LABELS)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
